# Generated by Django 5.0.1 on 2024-01-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('peoples', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(default=1, verbose_name='Оценка')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='main.studentgroup', verbose_name='Группа')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='peoples.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
                'ordering': ('-student',),
            },
        ),
    ]
