# Generated by Django 5.0.1 on 2024-01-04 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 4, 10, 36, 57, 137008, tzinfo=datetime.timezone.utc), verbose_name='Дата поступления'),
        ),
    ]
