# Generated by Django 5.0.1 on 2024-01-04 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentgroup_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='date_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата поступления'),
        ),
    ]
