# Generated by Django 5.0.1 on 2024-01-04 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(default=datetime.datetime(1994, 1, 11, 10, 16, 49, 48862, tzinfo=datetime.timezone.utc), verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('-first_name',),
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('role', models.IntegerField(choices=[(1, 'Преподаватель'), (5, 'Заведующий'), (10, 'Декан')], default=1, verbose_name='Роль')),
                ('date_of_birth', models.DateField(default=datetime.date(1994, 1, 11), verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-first_name',),
            },
        ),
    ]
